# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180531_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='sex',
            field=models.TextField(default='male'),
        ),
    ]
