# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 19:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180531_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
