# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='hello this is the article you have been waiting for.'),
        ),
    ]
